server:
  name: "kd48"
  env: "dev"

gateway:
  port: 8080

user_service:
  port: 9000

log:
  level: "debug" # debug, info, warn, error

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

etcd:
  endpoints:
    - "localhost:2379"