// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gateway/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         string                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	JsonPayload   []byte                 `protobuf:"bytes,2,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	Baggage       map[string]string      `protobuf:"bytes,3,rep,name=baggage,proto3" json:"baggage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngressRequest) Reset() {
	*x = IngressRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngressRequest) ProtoMessage() {}

func (x *IngressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngressRequest.ProtoReflect.Descriptor instead.
func (*IngressRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *IngressRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *IngressRequest) GetJsonPayload() []byte {
	if x != nil {
		return x.JsonPayload
	}
	return nil
}

func (x *IngressRequest) GetBaggage() map[string]string {
	if x != nil {
		return x.Baggage
	}
	return nil
}

type IngressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPayload   []byte                 `protobuf:"bytes,1,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngressReply) Reset() {
	*x = IngressReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngressReply) ProtoMessage() {}

func (x *IngressReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngressReply.ProtoReflect.Descriptor instead.
func (*IngressReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *IngressReply) GetJsonPayload() []byte {
	if x != nil {
		return x.JsonPayload
	}
	return nil
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\"\xc8\x01\n" +
	"\x0eIngressRequest\x12\x14\n" +
	"\x05route\x18\x01 \x01(\tR\x05route\x12!\n" +
	"\fjson_payload\x18\x02 \x01(\fR\vjsonPayload\x12A\n" +
	"\abaggage\x18\x03 \x03(\v2'.gateway.v1.IngressRequest.BaggageEntryR\abaggage\x1a:\n" +
	"\fBaggageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\fIngressReply\x12!\n" +
	"\fjson_payload\x18\x01 \x01(\fR\vjsonPayload2N\n" +
	"\x0eGatewayIngress\x12<\n" +
	"\x04Call\x12\x1a.gateway.v1.IngressRequest\x1a\x18.gateway.v1.IngressReplyB9Z7github.com/CBookShu/kd48/api/proto/gateway/v1;gatewayv1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*IngressRequest)(nil), // 0: gateway.v1.IngressRequest
	(*IngressReply)(nil),   // 1: gateway.v1.IngressReply
	nil,                    // 2: gateway.v1.IngressRequest.BaggageEntry
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	2, // 0: gateway.v1.IngressRequest.baggage:type_name -> gateway.v1.IngressRequest.BaggageEntry
	0, // 1: gateway.v1.GatewayIngress.Call:input_type -> gateway.v1.IngressRequest
	1, // 2: gateway.v1.GatewayIngress.Call:output_type -> gateway.v1.IngressReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
