// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gateway/v1/gateway_route.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayRouteSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // 当前规范为 1
	// 须与 Etcd key 中 {route_id} 一致
	RouteId string `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	// 与客户端 WS 信封 `method` 全字匹配（v0.1）
	WsMethod string `protobuf:"bytes,3,opt,name=ws_method,json=wsMethod,proto3" json:"ws_method,omitempty"`
	// 引用 ServiceTypeSpec.type_key（须已存在且 v0.1 下为 STATELESS_LB）
	ServiceType string `protobuf:"bytes,4,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	// 传入 GatewayIngress.Call 的 route 字段
	IngressRoute string `protobuf:"bytes,5,opt,name=ingress_route,json=ingressRoute,proto3" json:"ingress_route,omitempty"`
	// true：免鉴权；false：须已认证（替代 handler 内后缀硬编码）
	Public bool `protobuf:"varint,6,opt,name=public,proto3" json:"public,omitempty"`
	// 可选，便于运维展示
	DisplayName   string `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRouteSpec) Reset() {
	*x = GatewayRouteSpec{}
	mi := &file_gateway_v1_gateway_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRouteSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRouteSpec) ProtoMessage() {}

func (x *GatewayRouteSpec) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRouteSpec.ProtoReflect.Descriptor instead.
func (*GatewayRouteSpec) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_route_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayRouteSpec) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *GatewayRouteSpec) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *GatewayRouteSpec) GetWsMethod() string {
	if x != nil {
		return x.WsMethod
	}
	return ""
}

func (x *GatewayRouteSpec) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *GatewayRouteSpec) GetIngressRoute() string {
	if x != nil {
		return x.IngressRoute
	}
	return ""
}

func (x *GatewayRouteSpec) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *GatewayRouteSpec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_gateway_v1_gateway_route_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_route_proto_rawDesc = "" +
	"\n" +
	"\x1egateway/v1/gateway_route.proto\x12\n" +
	"gateway.v1\"\xf4\x01\n" +
	"\x10GatewayRouteSpec\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x1b\n" +
	"\tws_method\x18\x03 \x01(\tR\bwsMethod\x12!\n" +
	"\fservice_type\x18\x04 \x01(\tR\vserviceType\x12#\n" +
	"\ringress_route\x18\x05 \x01(\tR\fingressRoute\x12\x16\n" +
	"\x06public\x18\x06 \x01(\bR\x06public\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayNameB9Z7github.com/CBookShu/kd48/api/proto/gateway/v1;gatewayv1b\x06proto3"

var (
	file_gateway_v1_gateway_route_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_route_proto_rawDescData []byte
)

func file_gateway_v1_gateway_route_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_route_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_route_proto_rawDesc), len(file_gateway_v1_gateway_route_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_route_proto_rawDescData
}

var file_gateway_v1_gateway_route_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_v1_gateway_route_proto_goTypes = []any{
	(*GatewayRouteSpec)(nil), // 0: gateway.v1.GatewayRouteSpec
}
var file_gateway_v1_gateway_route_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_route_proto_init() }
func file_gateway_v1_gateway_route_proto_init() {
	if File_gateway_v1_gateway_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_route_proto_rawDesc), len(file_gateway_v1_gateway_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_gateway_route_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_route_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_route_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_route_proto = out.File
	file_gateway_v1_gateway_route_proto_goTypes = nil
	file_gateway_v1_gateway_route_proto_depIdxs = nil
}
