// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: gateway/v1/gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayIngress_Call_FullMethodName = "/gateway.v1.GatewayIngress/Call"
)

// GatewayIngressClient is the client API for GatewayIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayIngressClient interface {
	Call(ctx context.Context, in *IngressRequest, opts ...grpc.CallOption) (*IngressReply, error)
}

type gatewayIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayIngressClient(cc grpc.ClientConnInterface) GatewayIngressClient {
	return &gatewayIngressClient{cc}
}

func (c *gatewayIngressClient) Call(ctx context.Context, in *IngressRequest, opts ...grpc.CallOption) (*IngressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngressReply)
	err := c.cc.Invoke(ctx, GatewayIngress_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayIngressServer is the server API for GatewayIngress service.
// All implementations must embed UnimplementedGatewayIngressServer
// for forward compatibility.
type GatewayIngressServer interface {
	Call(context.Context, *IngressRequest) (*IngressReply, error)
	mustEmbedUnimplementedGatewayIngressServer()
}

// UnimplementedGatewayIngressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayIngressServer struct{}

func (UnimplementedGatewayIngressServer) Call(context.Context, *IngressRequest) (*IngressReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedGatewayIngressServer) mustEmbedUnimplementedGatewayIngressServer() {}
func (UnimplementedGatewayIngressServer) testEmbeddedByValue()                        {}

// UnsafeGatewayIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayIngressServer will
// result in compilation errors.
type UnsafeGatewayIngressServer interface {
	mustEmbedUnimplementedGatewayIngressServer()
}

func RegisterGatewayIngressServer(s grpc.ServiceRegistrar, srv GatewayIngressServer) {
	// If the following call panics, it indicates UnimplementedGatewayIngressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayIngress_ServiceDesc, srv)
}

func _GatewayIngress_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayIngressServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayIngress_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayIngressServer).Call(ctx, req.(*IngressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayIngress_ServiceDesc is the grpc.ServiceDesc for GatewayIngress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayIngress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.GatewayIngress",
	HandlerType: (*GatewayIngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _GatewayIngress_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/v1/gateway.proto",
}
