// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gateway/v1/service_type.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 路由语义；网关实现可分期启用。
type ServiceRoutingMode int32

const (
	ServiceRoutingMode_SERVICE_ROUTING_MODE_UNSPECIFIED ServiceRoutingMode = 0
	// 无状态：统一前缀 + 多实例 LB（当前网关 v0.1 仅接受本枚举值）
	ServiceRoutingMode_SERVICE_ROUTING_MODE_STATELESS_LB ServiceRoutingMode = 1
)

// Enum value maps for ServiceRoutingMode.
var (
	ServiceRoutingMode_name = map[int32]string{
		0: "SERVICE_ROUTING_MODE_UNSPECIFIED",
		1: "SERVICE_ROUTING_MODE_STATELESS_LB",
	}
	ServiceRoutingMode_value = map[string]int32{
		"SERVICE_ROUTING_MODE_UNSPECIFIED":  0,
		"SERVICE_ROUTING_MODE_STATELESS_LB": 1,
	}
)

func (x ServiceRoutingMode) Enum() *ServiceRoutingMode {
	p := new(ServiceRoutingMode)
	*p = x
	return p
}

func (x ServiceRoutingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceRoutingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_service_type_proto_enumTypes[0].Descriptor()
}

func (ServiceRoutingMode) Type() protoreflect.EnumType {
	return &file_gateway_v1_service_type_proto_enumTypes[0]
}

func (x ServiceRoutingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceRoutingMode.Descriptor instead.
func (ServiceRoutingMode) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_service_type_proto_rawDescGZIP(), []int{0}
}

// 与 gRPC 发现 target 对应（通常指向实例注册所用 Etcd 前缀）。
type ServiceTypeDiscovery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 例：etcd:///kd48/user-service
	GrpcEtcdTarget string `protobuf:"bytes,1,opt,name=grpc_etcd_target,json=grpcEtcdTarget,proto3" json:"grpc_etcd_target,omitempty"`
	// 可选；与 grpc.WithDefaultServiceConfig 对齐，默认 round_robin
	LoadBalancing string `protobuf:"bytes,2,opt,name=load_balancing,json=loadBalancing,proto3" json:"load_balancing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTypeDiscovery) Reset() {
	*x = ServiceTypeDiscovery{}
	mi := &file_gateway_v1_service_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTypeDiscovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTypeDiscovery) ProtoMessage() {}

func (x *ServiceTypeDiscovery) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_service_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTypeDiscovery.ProtoReflect.Descriptor instead.
func (*ServiceTypeDiscovery) Descriptor() ([]byte, []int) {
	return file_gateway_v1_service_type_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceTypeDiscovery) GetGrpcEtcdTarget() string {
	if x != nil {
		return x.GrpcEtcdTarget
	}
	return ""
}

func (x *ServiceTypeDiscovery) GetLoadBalancing() string {
	if x != nil {
		return x.LoadBalancing
	}
	return ""
}

type ServiceTypeIngress struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UseGatewayIngress bool                   `protobuf:"varint,1,opt,name=use_gateway_ingress,json=useGatewayIngress,proto3" json:"use_gateway_ingress,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceTypeIngress) Reset() {
	*x = ServiceTypeIngress{}
	mi := &file_gateway_v1_service_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTypeIngress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTypeIngress) ProtoMessage() {}

func (x *ServiceTypeIngress) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_service_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTypeIngress.ProtoReflect.Descriptor instead.
func (*ServiceTypeIngress) Descriptor() ([]byte, []int) {
	return file_gateway_v1_service_type_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceTypeIngress) GetUseGatewayIngress() bool {
	if x != nil {
		return x.UseGatewayIngress
	}
	return false
}

type ServiceTypeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // 当前规范为 1
	// 须与 Etcd key 中 {type_key} 一致
	TypeKey       string                `protobuf:"bytes,2,opt,name=type_key,json=typeKey,proto3" json:"type_key,omitempty"`
	DisplayName   string                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RoutingMode   ServiceRoutingMode    `protobuf:"varint,4,opt,name=routing_mode,json=routingMode,proto3,enum=gateway.v1.ServiceRoutingMode" json:"routing_mode,omitempty"`
	Discovery     *ServiceTypeDiscovery `protobuf:"bytes,5,opt,name=discovery,proto3" json:"discovery,omitempty"`
	Ingress       *ServiceTypeIngress   `protobuf:"bytes,6,opt,name=ingress,proto3" json:"ingress,omitempty"`
	UpdatedAtUnix int64                 `protobuf:"varint,7,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTypeSpec) Reset() {
	*x = ServiceTypeSpec{}
	mi := &file_gateway_v1_service_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTypeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTypeSpec) ProtoMessage() {}

func (x *ServiceTypeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_service_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTypeSpec.ProtoReflect.Descriptor instead.
func (*ServiceTypeSpec) Descriptor() ([]byte, []int) {
	return file_gateway_v1_service_type_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceTypeSpec) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ServiceTypeSpec) GetTypeKey() string {
	if x != nil {
		return x.TypeKey
	}
	return ""
}

func (x *ServiceTypeSpec) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ServiceTypeSpec) GetRoutingMode() ServiceRoutingMode {
	if x != nil {
		return x.RoutingMode
	}
	return ServiceRoutingMode_SERVICE_ROUTING_MODE_UNSPECIFIED
}

func (x *ServiceTypeSpec) GetDiscovery() *ServiceTypeDiscovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *ServiceTypeSpec) GetIngress() *ServiceTypeIngress {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *ServiceTypeSpec) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

var File_gateway_v1_service_type_proto protoreflect.FileDescriptor

const file_gateway_v1_service_type_proto_rawDesc = "" +
	"\n" +
	"\x1dgateway/v1/service_type.proto\x12\n" +
	"gateway.v1\"g\n" +
	"\x14ServiceTypeDiscovery\x12(\n" +
	"\x10grpc_etcd_target\x18\x01 \x01(\tR\x0egrpcEtcdTarget\x12%\n" +
	"\x0eload_balancing\x18\x02 \x01(\tR\rloadBalancing\"D\n" +
	"\x12ServiceTypeIngress\x12.\n" +
	"\x13use_gateway_ingress\x18\x01 \x01(\bR\x11useGatewayIngress\"\xdb\x02\n" +
	"\x0fServiceTypeSpec\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x19\n" +
	"\btype_key\x18\x02 \x01(\tR\atypeKey\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12A\n" +
	"\frouting_mode\x18\x04 \x01(\x0e2\x1e.gateway.v1.ServiceRoutingModeR\vroutingMode\x12>\n" +
	"\tdiscovery\x18\x05 \x01(\v2 .gateway.v1.ServiceTypeDiscoveryR\tdiscovery\x128\n" +
	"\aingress\x18\x06 \x01(\v2\x1e.gateway.v1.ServiceTypeIngressR\aingress\x12&\n" +
	"\x0fupdated_at_unix\x18\a \x01(\x03R\rupdatedAtUnix*a\n" +
	"\x12ServiceRoutingMode\x12$\n" +
	" SERVICE_ROUTING_MODE_UNSPECIFIED\x10\x00\x12%\n" +
	"!SERVICE_ROUTING_MODE_STATELESS_LB\x10\x01B9Z7github.com/CBookShu/kd48/api/proto/gateway/v1;gatewayv1b\x06proto3"

var (
	file_gateway_v1_service_type_proto_rawDescOnce sync.Once
	file_gateway_v1_service_type_proto_rawDescData []byte
)

func file_gateway_v1_service_type_proto_rawDescGZIP() []byte {
	file_gateway_v1_service_type_proto_rawDescOnce.Do(func() {
		file_gateway_v1_service_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_service_type_proto_rawDesc), len(file_gateway_v1_service_type_proto_rawDesc)))
	})
	return file_gateway_v1_service_type_proto_rawDescData
}

var file_gateway_v1_service_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_v1_service_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_v1_service_type_proto_goTypes = []any{
	(ServiceRoutingMode)(0),      // 0: gateway.v1.ServiceRoutingMode
	(*ServiceTypeDiscovery)(nil), // 1: gateway.v1.ServiceTypeDiscovery
	(*ServiceTypeIngress)(nil),   // 2: gateway.v1.ServiceTypeIngress
	(*ServiceTypeSpec)(nil),      // 3: gateway.v1.ServiceTypeSpec
}
var file_gateway_v1_service_type_proto_depIdxs = []int32{
	0, // 0: gateway.v1.ServiceTypeSpec.routing_mode:type_name -> gateway.v1.ServiceRoutingMode
	1, // 1: gateway.v1.ServiceTypeSpec.discovery:type_name -> gateway.v1.ServiceTypeDiscovery
	2, // 2: gateway.v1.ServiceTypeSpec.ingress:type_name -> gateway.v1.ServiceTypeIngress
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_v1_service_type_proto_init() }
func file_gateway_v1_service_type_proto_init() {
	if File_gateway_v1_service_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_service_type_proto_rawDesc), len(file_gateway_v1_service_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_service_type_proto_goTypes,
		DependencyIndexes: file_gateway_v1_service_type_proto_depIdxs,
		EnumInfos:         file_gateway_v1_service_type_proto_enumTypes,
		MessageInfos:      file_gateway_v1_service_type_proto_msgTypes,
	}.Build()
	File_gateway_v1_service_type_proto = out.File
	file_gateway_v1_service_type_proto_goTypes = nil
	file_gateway_v1_service_type_proto_depIdxs = nil
}
