// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type User struct {
	ID uint64 `json:"id"`
	// 用户名，唯一
	Username string `json:"username"`
	// bcrypt 加密后的密码
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
