// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common/v1/api_response.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode 错误码定义（所有服务共用）
// 规则：每个模块预分配 1000 个码
type ErrorCode int32

const (
	ErrorCode_SUCCESS ErrorCode = 0
	// 系统错误 1000-1999
	ErrorCode_INVALID_REQUEST     ErrorCode = 1000
	ErrorCode_INTERNAL_ERROR      ErrorCode = 1001
	ErrorCode_SERVICE_UNAVAILABLE ErrorCode = 1002
	// 用户相关 2000-2999
	ErrorCode_USER_NOT_FOUND         ErrorCode = 2000
	ErrorCode_USER_NOT_AUTHENTICATED ErrorCode = 2001
	// 签到相关 3000-3999
	ErrorCode_CHECKIN_ALREADY_TODAY     ErrorCode = 3000
	ErrorCode_CHECKIN_PERIOD_NOT_ACTIVE ErrorCode = 3001
	ErrorCode_CHECKIN_PERIOD_EXPIRED    ErrorCode = 3002
	// 物品相关 4000-4999
	ErrorCode_ITEM_NOT_FOUND    ErrorCode = 4000
	ErrorCode_ITEM_INSUFFICIENT ErrorCode = 4001
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:    "SUCCESS",
		1000: "INVALID_REQUEST",
		1001: "INTERNAL_ERROR",
		1002: "SERVICE_UNAVAILABLE",
		2000: "USER_NOT_FOUND",
		2001: "USER_NOT_AUTHENTICATED",
		3000: "CHECKIN_ALREADY_TODAY",
		3001: "CHECKIN_PERIOD_NOT_ACTIVE",
		3002: "CHECKIN_PERIOD_EXPIRED",
		4000: "ITEM_NOT_FOUND",
		4001: "ITEM_INSUFFICIENT",
	}
	ErrorCode_value = map[string]int32{
		"SUCCESS":                   0,
		"INVALID_REQUEST":           1000,
		"INTERNAL_ERROR":            1001,
		"SERVICE_UNAVAILABLE":       1002,
		"USER_NOT_FOUND":            2000,
		"USER_NOT_AUTHENTICATED":    2001,
		"CHECKIN_ALREADY_TODAY":     3000,
		"CHECKIN_PERIOD_NOT_ACTIVE": 3001,
		"CHECKIN_PERIOD_EXPIRED":    3002,
		"ITEM_NOT_FOUND":            4000,
		"ITEM_INSUFFICIENT":         4001,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_api_response_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_v1_api_response_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_api_response_proto_rawDescGZIP(), []int{0}
}

// ApiResponse 通用响应外壳（所有服务共用）
type ApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_common_v1_api_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_api_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_api_response_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_common_v1_api_response_proto protoreflect.FileDescriptor

const file_common_v1_api_response_proto_rawDesc = "" +
	"\n" +
	"\x1ccommon/v1/api_response.proto\x12\tcommon.v1\x1a\x19google/protobuf/any.proto\"\xd4\x01\n" +
	"\vApiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\x124\n" +
	"\x04meta\x18\x04 \x03(\v2 .common.v1.ApiResponse.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x95\x02\n" +
	"\tErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x14\n" +
	"\x0fINVALID_REQUEST\x10\xe8\a\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\xe9\a\x12\x18\n" +
	"\x13SERVICE_UNAVAILABLE\x10\xea\a\x12\x13\n" +
	"\x0eUSER_NOT_FOUND\x10\xd0\x0f\x12\x1b\n" +
	"\x16USER_NOT_AUTHENTICATED\x10\xd1\x0f\x12\x1a\n" +
	"\x15CHECKIN_ALREADY_TODAY\x10\xb8\x17\x12\x1e\n" +
	"\x19CHECKIN_PERIOD_NOT_ACTIVE\x10\xb9\x17\x12\x1b\n" +
	"\x16CHECKIN_PERIOD_EXPIRED\x10\xba\x17\x12\x13\n" +
	"\x0eITEM_NOT_FOUND\x10\xa0\x1f\x12\x16\n" +
	"\x11ITEM_INSUFFICIENT\x10\xa1\x1fB7Z5github.com/CBookShu/kd48/api/proto/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_api_response_proto_rawDescOnce sync.Once
	file_common_v1_api_response_proto_rawDescData []byte
)

func file_common_v1_api_response_proto_rawDescGZIP() []byte {
	file_common_v1_api_response_proto_rawDescOnce.Do(func() {
		file_common_v1_api_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_api_response_proto_rawDesc), len(file_common_v1_api_response_proto_rawDesc)))
	})
	return file_common_v1_api_response_proto_rawDescData
}

var file_common_v1_api_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_api_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_v1_api_response_proto_goTypes = []any{
	(ErrorCode)(0),      // 0: common.v1.ErrorCode
	(*ApiResponse)(nil), // 1: common.v1.ApiResponse
	nil,                 // 2: common.v1.ApiResponse.MetaEntry
	(*anypb.Any)(nil),   // 3: google.protobuf.Any
}
var file_common_v1_api_response_proto_depIdxs = []int32{
	3, // 0: common.v1.ApiResponse.data:type_name -> google.protobuf.Any
	2, // 1: common.v1.ApiResponse.meta:type_name -> common.v1.ApiResponse.MetaEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_v1_api_response_proto_init() }
func file_common_v1_api_response_proto_init() {
	if File_common_v1_api_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_api_response_proto_rawDesc), len(file_common_v1_api_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_api_response_proto_goTypes,
		DependencyIndexes: file_common_v1_api_response_proto_depIdxs,
		EnumInfos:         file_common_v1_api_response_proto_enumTypes,
		MessageInfos:      file_common_v1_api_response_proto_msgTypes,
	}.Build()
	File_common_v1_api_response_proto = out.File
	file_common_v1_api_response_proto_goTypes = nil
	file_common_v1_api_response_proto_depIdxs = nil
}
