package gogen

import (
	"fmt"
	"strings"

	"github.com/CBookShu/kd48/tools/config-loader/internal/csvparser"
)

type GoGenerator struct{}

func NewGenerator() *GoGenerator {
	return &GoGenerator{}
}

func (g *GoGenerator) Generate(sheet *csvparser.Sheet, pkgName string) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Code generated by config-loader. DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	hasTime := false
	for _, h := range sheet.Headers {
		if h.Type == "time" {
			hasTime = true
			break
		}
	}

	if hasTime {
		sb.WriteString(g.generateImports())
		sb.WriteString(g.generateConfigTime())
	}

	sb.WriteString(g.generateRowStruct(sheet))
	sb.WriteString(g.generateConfigStruct(sheet))
	sb.WriteString(g.generateParseFunc(sheet))

	return sb.String(), nil
}

func (g *GoGenerator) generateImports() string {
	return `import (
    "encoding/json"
    "time"
)

`
}

func (g *GoGenerator) generateConfigTime() string {
	return `// TimeFormat 配置时间格式
const TimeFormat = "2006-01-02 15:04:05"

// ConfigTime 包装 time.Time，支持自定义 JSON 解析
type ConfigTime struct {
    Raw  string    ` + "`json:\"-\"`" + `
    Time time.Time ` + "`json:\"-\"`" + `
}

func (t *ConfigTime) UnmarshalJSON(data []byte) error {
    var s string
    if err := json.Unmarshal(data, &s); err != nil {
        return err
    }
    t.Raw = s
    parsed, err := time.ParseInLocation(TimeFormat, s, time.Local)
    if err != nil {
        return err
    }
    t.Time = parsed
    return nil
}

func (t ConfigTime) MarshalJSON() ([]byte, error) {
    return json.Marshal(t.Raw)
}

func (t ConfigTime) String() string {
    return t.Raw
}

`
}

func (g *GoGenerator) generateRowStruct(sheet *csvparser.Sheet) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("// %sRow 表示配置数据行\n", sheet.ConfigName))
	sb.WriteString(fmt.Sprintf("type %sRow struct {\n", sheet.ConfigName))

	for _, h := range sheet.Headers {
		goType := g.csvTypeToGoType(h.Type)
		sb.WriteString(fmt.Sprintf("    %s %s `json:\"%s\"`\n", g.toCamelCase(h.Name), goType, h.Name))
	}

	sb.WriteString("}\n\n")
	return sb.String()
}

func (g *GoGenerator) generateConfigStruct(sheet *csvparser.Sheet) string {
	return fmt.Sprintf(`// %sConfig 表示完整配置
type %sConfig struct {
    ConfigName string       `+"`json:\"config_name\"`"+`
    Revision   int64        `+"`json:\"revision\"`"+`
    Data       []%sRow `+"`json:\"data\"`"+`
}

`, sheet.ConfigName, sheet.ConfigName, sheet.ConfigName)
}

func (g *GoGenerator) generateParseFunc(sheet *csvparser.Sheet) string {
	return fmt.Sprintf(`// Parse%sConfig 从 JSON 解析配置
func Parse%sConfig(data []byte) (*%sConfig, error) {
    var cfg %sConfig
    if err := json.Unmarshal(data, &cfg); err != nil {
        return nil, err
    }
    return &cfg, nil
}
`, sheet.ConfigName, sheet.ConfigName, sheet.ConfigName, sheet.ConfigName)
}

func (g *GoGenerator) csvTypeToGoType(csvType string) string {
	switch csvType {
	case "int32":
		return "int32"
	case "int64":
		return "int64"
	case "string":
		return "string"
	case "time":
		return "ConfigTime"
	case "int32[]":
		return "[]int32"
	case "int64[]":
		return "[]int64"
	case "string[]":
		return "[]string"
	default:
		if strings.Contains(csvType, "=") {
			return g.parseMapType(csvType)
		}
		return "string"
	}
}

func (g *GoGenerator) parseMapType(csvType string) string {
	parts := strings.Split(csvType, "=")
	keyType := strings.TrimSpace(parts[0])
	valueType := strings.TrimSpace(parts[1])

	keyGo := "string"
	if keyType == "int32" || keyType == "int64" {
		keyGo = keyType
	}

	valueGo := "string"
	if valueType == "int32" || valueType == "int64" {
		valueGo = valueType
	}

	return fmt.Sprintf("map[%s]%s", keyGo, valueGo)
}

func (g *GoGenerator) toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}
