// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: lobby/v1/checkin.proto

package lobbyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckinService_Checkin_FullMethodName   = "/lobby.v1.CheckinService/Checkin"
	CheckinService_GetStatus_FullMethodName = "/lobby.v1.CheckinService/GetStatus"
)

// CheckinServiceClient is the client API for CheckinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CheckinService 签到服务
type CheckinServiceClient interface {
	Checkin(ctx context.Context, in *CheckinRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*ApiResponse, error)
}

type checkinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckinServiceClient(cc grpc.ClientConnInterface) CheckinServiceClient {
	return &checkinServiceClient{cc}
}

func (c *checkinServiceClient) Checkin(ctx context.Context, in *CheckinRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, CheckinService_Checkin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, CheckinService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckinServiceServer is the server API for CheckinService service.
// All implementations must embed UnimplementedCheckinServiceServer
// for forward compatibility.
//
// CheckinService 签到服务
type CheckinServiceServer interface {
	Checkin(context.Context, *CheckinRequest) (*ApiResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*ApiResponse, error)
	mustEmbedUnimplementedCheckinServiceServer()
}

// UnimplementedCheckinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckinServiceServer struct{}

func (UnimplementedCheckinServiceServer) Checkin(context.Context, *CheckinRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkin not implemented")
}
func (UnimplementedCheckinServiceServer) GetStatus(context.Context, *GetStatusRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedCheckinServiceServer) mustEmbedUnimplementedCheckinServiceServer() {}
func (UnimplementedCheckinServiceServer) testEmbeddedByValue()                        {}

// UnsafeCheckinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckinServiceServer will
// result in compilation errors.
type UnsafeCheckinServiceServer interface {
	mustEmbedUnimplementedCheckinServiceServer()
}

func RegisterCheckinServiceServer(s grpc.ServiceRegistrar, srv CheckinServiceServer) {
	// If the following call panics, it indicates UnimplementedCheckinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckinService_ServiceDesc, srv)
}

func _CheckinService_Checkin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).Checkin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckinService_Checkin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).Checkin(ctx, req.(*CheckinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckinService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckinService_ServiceDesc is the grpc.ServiceDesc for CheckinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobby.v1.CheckinService",
	HandlerType: (*CheckinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Checkin",
			Handler:    _CheckinService_Checkin_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _CheckinService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lobby/v1/checkin.proto",
}
