// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: lobby/v1/checkin.proto

package lobbyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckinRequest) Reset() {
	*x = CheckinRequest{}
	mi := &file_lobby_v1_checkin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinRequest) ProtoMessage() {}

func (x *CheckinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_checkin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinRequest.ProtoReflect.Descriptor instead.
func (*CheckinRequest) Descriptor() ([]byte, []int) {
	return file_lobby_v1_checkin_proto_rawDescGZIP(), []int{0}
}

type CheckinData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContinuousDays int32                  `protobuf:"varint,1,opt,name=continuous_days,json=continuousDays,proto3" json:"continuous_days,omitempty"`
	Rewards        map[int32]int64        `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckinData) Reset() {
	*x = CheckinData{}
	mi := &file_lobby_v1_checkin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinData) ProtoMessage() {}

func (x *CheckinData) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_checkin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinData.ProtoReflect.Descriptor instead.
func (*CheckinData) Descriptor() ([]byte, []int) {
	return file_lobby_v1_checkin_proto_rawDescGZIP(), []int{1}
}

func (x *CheckinData) GetContinuousDays() int32 {
	if x != nil {
		return x.ContinuousDays
	}
	return 0
}

func (x *CheckinData) GetRewards() map[int32]int64 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_lobby_v1_checkin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_checkin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_lobby_v1_checkin_proto_rawDescGZIP(), []int{2}
}

type CheckinStatusData struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	PeriodId          int64                   `protobuf:"varint,1,opt,name=period_id,json=periodId,proto3" json:"period_id,omitempty"`
	PeriodName        string                  `protobuf:"bytes,2,opt,name=period_name,json=periodName,proto3" json:"period_name,omitempty"`
	DailyRewards      []*DailyRewardInfo      `protobuf:"bytes,3,rep,name=daily_rewards,json=dailyRewards,proto3" json:"daily_rewards,omitempty"`
	ContinuousRewards []*ContinuousRewardInfo `protobuf:"bytes,4,rep,name=continuous_rewards,json=continuousRewards,proto3" json:"continuous_rewards,omitempty"`
	TodayChecked      bool                    `protobuf:"varint,10,opt,name=today_checked,json=todayChecked,proto3" json:"today_checked,omitempty"`
	ContinuousDays    int32                   `protobuf:"varint,11,opt,name=continuous_days,json=continuousDays,proto3" json:"continuous_days,omitempty"`
	TotalDays         int32                   `protobuf:"varint,12,opt,name=total_days,json=totalDays,proto3" json:"total_days,omitempty"`
	ClaimedContinuous []int32                 `protobuf:"varint,13,rep,packed,name=claimed_continuous,json=claimedContinuous,proto3" json:"claimed_continuous,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckinStatusData) Reset() {
	*x = CheckinStatusData{}
	mi := &file_lobby_v1_checkin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckinStatusData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinStatusData) ProtoMessage() {}

func (x *CheckinStatusData) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_checkin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinStatusData.ProtoReflect.Descriptor instead.
func (*CheckinStatusData) Descriptor() ([]byte, []int) {
	return file_lobby_v1_checkin_proto_rawDescGZIP(), []int{3}
}

func (x *CheckinStatusData) GetPeriodId() int64 {
	if x != nil {
		return x.PeriodId
	}
	return 0
}

func (x *CheckinStatusData) GetPeriodName() string {
	if x != nil {
		return x.PeriodName
	}
	return ""
}

func (x *CheckinStatusData) GetDailyRewards() []*DailyRewardInfo {
	if x != nil {
		return x.DailyRewards
	}
	return nil
}

func (x *CheckinStatusData) GetContinuousRewards() []*ContinuousRewardInfo {
	if x != nil {
		return x.ContinuousRewards
	}
	return nil
}

func (x *CheckinStatusData) GetTodayChecked() bool {
	if x != nil {
		return x.TodayChecked
	}
	return false
}

func (x *CheckinStatusData) GetContinuousDays() int32 {
	if x != nil {
		return x.ContinuousDays
	}
	return 0
}

func (x *CheckinStatusData) GetTotalDays() int32 {
	if x != nil {
		return x.TotalDays
	}
	return 0
}

func (x *CheckinStatusData) GetClaimedContinuous() []int32 {
	if x != nil {
		return x.ClaimedContinuous
	}
	return nil
}

type DailyRewardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Rewards       map[int32]int64        `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyRewardInfo) Reset() {
	*x = DailyRewardInfo{}
	mi := &file_lobby_v1_checkin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyRewardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyRewardInfo) ProtoMessage() {}

func (x *DailyRewardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_checkin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyRewardInfo.ProtoReflect.Descriptor instead.
func (*DailyRewardInfo) Descriptor() ([]byte, []int) {
	return file_lobby_v1_checkin_proto_rawDescGZIP(), []int{4}
}

func (x *DailyRewardInfo) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *DailyRewardInfo) GetRewards() map[int32]int64 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type ContinuousRewardInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContinuousDays int32                  `protobuf:"varint,1,opt,name=continuous_days,json=continuousDays,proto3" json:"continuous_days,omitempty"`
	Rewards        map[int32]int64        `protobuf:"bytes,2,rep,name=rewards,proto3" json:"rewards,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContinuousRewardInfo) Reset() {
	*x = ContinuousRewardInfo{}
	mi := &file_lobby_v1_checkin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinuousRewardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinuousRewardInfo) ProtoMessage() {}

func (x *ContinuousRewardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_checkin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinuousRewardInfo.ProtoReflect.Descriptor instead.
func (*ContinuousRewardInfo) Descriptor() ([]byte, []int) {
	return file_lobby_v1_checkin_proto_rawDescGZIP(), []int{5}
}

func (x *ContinuousRewardInfo) GetContinuousDays() int32 {
	if x != nil {
		return x.ContinuousDays
	}
	return 0
}

func (x *ContinuousRewardInfo) GetRewards() map[int32]int64 {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_lobby_v1_checkin_proto protoreflect.FileDescriptor

const file_lobby_v1_checkin_proto_rawDesc = "" +
	"\n" +
	"\x16lobby/v1/checkin.proto\x12\blobby.v1\"\x10\n" +
	"\x0eCheckinRequest\"\xb0\x01\n" +
	"\vCheckinData\x12'\n" +
	"\x0fcontinuous_days\x18\x01 \x01(\x05R\x0econtinuousDays\x12<\n" +
	"\arewards\x18\x02 \x03(\v2\".lobby.v1.CheckinData.RewardsEntryR\arewards\x1a:\n" +
	"\fRewardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x12\n" +
	"\x10GetStatusRequest\"\xfc\x02\n" +
	"\x11CheckinStatusData\x12\x1b\n" +
	"\tperiod_id\x18\x01 \x01(\x03R\bperiodId\x12\x1f\n" +
	"\vperiod_name\x18\x02 \x01(\tR\n" +
	"periodName\x12>\n" +
	"\rdaily_rewards\x18\x03 \x03(\v2\x19.lobby.v1.DailyRewardInfoR\fdailyRewards\x12M\n" +
	"\x12continuous_rewards\x18\x04 \x03(\v2\x1e.lobby.v1.ContinuousRewardInfoR\x11continuousRewards\x12#\n" +
	"\rtoday_checked\x18\n" +
	" \x01(\bR\ftodayChecked\x12'\n" +
	"\x0fcontinuous_days\x18\v \x01(\x05R\x0econtinuousDays\x12\x1d\n" +
	"\n" +
	"total_days\x18\f \x01(\x05R\ttotalDays\x12-\n" +
	"\x12claimed_continuous\x18\r \x03(\x05R\x11claimedContinuous\"\xa1\x01\n" +
	"\x0fDailyRewardInfo\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12@\n" +
	"\arewards\x18\x02 \x03(\v2&.lobby.v1.DailyRewardInfo.RewardsEntryR\arewards\x1a:\n" +
	"\fRewardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xc2\x01\n" +
	"\x14ContinuousRewardInfo\x12'\n" +
	"\x0fcontinuous_days\x18\x01 \x01(\x05R\x0econtinuousDays\x12E\n" +
	"\arewards\x18\x02 \x03(\v2+.lobby.v1.ContinuousRewardInfo.RewardsEntryR\arewards\x1a:\n" +
	"\fRewardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\x92\x01\n" +
	"\x0eCheckinService\x12:\n" +
	"\aCheckin\x12\x18.lobby.v1.CheckinRequest\x1a\x15.lobby.v1.CheckinData\x12D\n" +
	"\tGetStatus\x12\x1a.lobby.v1.GetStatusRequest\x1a\x1b.lobby.v1.CheckinStatusDataB5Z3github.com/CBookShu/kd48/api/proto/lobby/v1;lobbyv1b\x06proto3"

var (
	file_lobby_v1_checkin_proto_rawDescOnce sync.Once
	file_lobby_v1_checkin_proto_rawDescData []byte
)

func file_lobby_v1_checkin_proto_rawDescGZIP() []byte {
	file_lobby_v1_checkin_proto_rawDescOnce.Do(func() {
		file_lobby_v1_checkin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lobby_v1_checkin_proto_rawDesc), len(file_lobby_v1_checkin_proto_rawDesc)))
	})
	return file_lobby_v1_checkin_proto_rawDescData
}

var file_lobby_v1_checkin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_lobby_v1_checkin_proto_goTypes = []any{
	(*CheckinRequest)(nil),       // 0: lobby.v1.CheckinRequest
	(*CheckinData)(nil),          // 1: lobby.v1.CheckinData
	(*GetStatusRequest)(nil),     // 2: lobby.v1.GetStatusRequest
	(*CheckinStatusData)(nil),    // 3: lobby.v1.CheckinStatusData
	(*DailyRewardInfo)(nil),      // 4: lobby.v1.DailyRewardInfo
	(*ContinuousRewardInfo)(nil), // 5: lobby.v1.ContinuousRewardInfo
	nil,                          // 6: lobby.v1.CheckinData.RewardsEntry
	nil,                          // 7: lobby.v1.DailyRewardInfo.RewardsEntry
	nil,                          // 8: lobby.v1.ContinuousRewardInfo.RewardsEntry
}
var file_lobby_v1_checkin_proto_depIdxs = []int32{
	6, // 0: lobby.v1.CheckinData.rewards:type_name -> lobby.v1.CheckinData.RewardsEntry
	4, // 1: lobby.v1.CheckinStatusData.daily_rewards:type_name -> lobby.v1.DailyRewardInfo
	5, // 2: lobby.v1.CheckinStatusData.continuous_rewards:type_name -> lobby.v1.ContinuousRewardInfo
	7, // 3: lobby.v1.DailyRewardInfo.rewards:type_name -> lobby.v1.DailyRewardInfo.RewardsEntry
	8, // 4: lobby.v1.ContinuousRewardInfo.rewards:type_name -> lobby.v1.ContinuousRewardInfo.RewardsEntry
	0, // 5: lobby.v1.CheckinService.Checkin:input_type -> lobby.v1.CheckinRequest
	2, // 6: lobby.v1.CheckinService.GetStatus:input_type -> lobby.v1.GetStatusRequest
	1, // 7: lobby.v1.CheckinService.Checkin:output_type -> lobby.v1.CheckinData
	3, // 8: lobby.v1.CheckinService.GetStatus:output_type -> lobby.v1.CheckinStatusData
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_lobby_v1_checkin_proto_init() }
func file_lobby_v1_checkin_proto_init() {
	if File_lobby_v1_checkin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lobby_v1_checkin_proto_rawDesc), len(file_lobby_v1_checkin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lobby_v1_checkin_proto_goTypes,
		DependencyIndexes: file_lobby_v1_checkin_proto_depIdxs,
		MessageInfos:      file_lobby_v1_checkin_proto_msgTypes,
	}.Build()
	File_lobby_v1_checkin_proto = out.File
	file_lobby_v1_checkin_proto_goTypes = nil
	file_lobby_v1_checkin_proto_depIdxs = nil
}
