// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: lobby/v1/item.proto

package lobbyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMyItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyItemsRequest) Reset() {
	*x = GetMyItemsRequest{}
	mi := &file_lobby_v1_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyItemsRequest) ProtoMessage() {}

func (x *GetMyItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyItemsRequest.ProtoReflect.Descriptor instead.
func (*GetMyItemsRequest) Descriptor() ([]byte, []int) {
	return file_lobby_v1_item_proto_rawDescGZIP(), []int{0}
}

type MyItemsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[int32]int64        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // item_id -> count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyItemsData) Reset() {
	*x = MyItemsData{}
	mi := &file_lobby_v1_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyItemsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyItemsData) ProtoMessage() {}

func (x *MyItemsData) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyItemsData.ProtoReflect.Descriptor instead.
func (*MyItemsData) Descriptor() ([]byte, []int) {
	return file_lobby_v1_item_proto_rawDescGZIP(), []int{1}
}

func (x *MyItemsData) GetItems() map[int32]int64 {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_lobby_v1_item_proto protoreflect.FileDescriptor

const file_lobby_v1_item_proto_rawDesc = "" +
	"\n" +
	"\x13lobby/v1/item.proto\x12\blobby.v1\"\x13\n" +
	"\x11GetMyItemsRequest\"\x7f\n" +
	"\vMyItemsData\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .lobby.v1.MyItemsData.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012O\n" +
	"\vItemService\x12@\n" +
	"\n" +
	"GetMyItems\x12\x1b.lobby.v1.GetMyItemsRequest\x1a\x15.lobby.v1.MyItemsDataB5Z3github.com/CBookShu/kd48/api/proto/lobby/v1;lobbyv1b\x06proto3"

var (
	file_lobby_v1_item_proto_rawDescOnce sync.Once
	file_lobby_v1_item_proto_rawDescData []byte
)

func file_lobby_v1_item_proto_rawDescGZIP() []byte {
	file_lobby_v1_item_proto_rawDescOnce.Do(func() {
		file_lobby_v1_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lobby_v1_item_proto_rawDesc), len(file_lobby_v1_item_proto_rawDesc)))
	})
	return file_lobby_v1_item_proto_rawDescData
}

var file_lobby_v1_item_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lobby_v1_item_proto_goTypes = []any{
	(*GetMyItemsRequest)(nil), // 0: lobby.v1.GetMyItemsRequest
	(*MyItemsData)(nil),       // 1: lobby.v1.MyItemsData
	nil,                       // 2: lobby.v1.MyItemsData.ItemsEntry
}
var file_lobby_v1_item_proto_depIdxs = []int32{
	2, // 0: lobby.v1.MyItemsData.items:type_name -> lobby.v1.MyItemsData.ItemsEntry
	0, // 1: lobby.v1.ItemService.GetMyItems:input_type -> lobby.v1.GetMyItemsRequest
	1, // 2: lobby.v1.ItemService.GetMyItems:output_type -> lobby.v1.MyItemsData
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lobby_v1_item_proto_init() }
func file_lobby_v1_item_proto_init() {
	if File_lobby_v1_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lobby_v1_item_proto_rawDesc), len(file_lobby_v1_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lobby_v1_item_proto_goTypes,
		DependencyIndexes: file_lobby_v1_item_proto_depIdxs,
		MessageInfos:      file_lobby_v1_item_proto_msgTypes,
	}.Build()
	File_lobby_v1_item_proto = out.File
	file_lobby_v1_item_proto_goTypes = nil
	file_lobby_v1_item_proto_depIdxs = nil
}
