// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: lobby/v1/lobby.proto

package lobbyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientHint    *string                `protobuf:"bytes,1,opt,name=client_hint,json=clientHint,proto3,oneof" json:"client_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_lobby_v1_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_lobby_v1_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetClientHint() string {
	if x != nil && x.ClientHint != nil {
		return *x.ClientHint
	}
	return ""
}

type PingReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pong           string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	ConfigRevision int64                  `protobuf:"varint,2,opt,name=config_revision,json=configRevision,proto3" json:"config_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_lobby_v1_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_v1_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_lobby_v1_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

func (x *PingReply) GetConfigRevision() int64 {
	if x != nil {
		return x.ConfigRevision
	}
	return 0
}

var File_lobby_v1_lobby_proto protoreflect.FileDescriptor

const file_lobby_v1_lobby_proto_rawDesc = "" +
	"\n" +
	"\x14lobby/v1/lobby.proto\x12\blobby.v1\"C\n" +
	"\vPingRequest\x12$\n" +
	"\vclient_hint\x18\x01 \x01(\tH\x00R\n" +
	"clientHint\x88\x01\x01B\x0e\n" +
	"\f_client_hint\"H\n" +
	"\tPingReply\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\x12'\n" +
	"\x0fconfig_revision\x18\x02 \x01(\x03R\x0econfigRevision2B\n" +
	"\fLobbyService\x122\n" +
	"\x04Ping\x12\x15.lobby.v1.PingRequest\x1a\x13.lobby.v1.PingReplyB5Z3github.com/CBookShu/kd48/api/proto/lobby/v1;lobbyv1b\x06proto3"

var (
	file_lobby_v1_lobby_proto_rawDescOnce sync.Once
	file_lobby_v1_lobby_proto_rawDescData []byte
)

func file_lobby_v1_lobby_proto_rawDescGZIP() []byte {
	file_lobby_v1_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_v1_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lobby_v1_lobby_proto_rawDesc), len(file_lobby_v1_lobby_proto_rawDesc)))
	})
	return file_lobby_v1_lobby_proto_rawDescData
}

var file_lobby_v1_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lobby_v1_lobby_proto_goTypes = []any{
	(*PingRequest)(nil), // 0: lobby.v1.PingRequest
	(*PingReply)(nil),   // 1: lobby.v1.PingReply
}
var file_lobby_v1_lobby_proto_depIdxs = []int32{
	0, // 0: lobby.v1.LobbyService.Ping:input_type -> lobby.v1.PingRequest
	1, // 1: lobby.v1.LobbyService.Ping:output_type -> lobby.v1.PingReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lobby_v1_lobby_proto_init() }
func file_lobby_v1_lobby_proto_init() {
	if File_lobby_v1_lobby_proto != nil {
		return
	}
	file_lobby_v1_lobby_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lobby_v1_lobby_proto_rawDesc), len(file_lobby_v1_lobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lobby_v1_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_v1_lobby_proto_depIdxs,
		MessageInfos:      file_lobby_v1_lobby_proto_msgTypes,
	}.Build()
	File_lobby_v1_lobby_proto = out.File
	file_lobby_v1_lobby_proto_goTypes = nil
	file_lobby_v1_lobby_proto_depIdxs = nil
}
