// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/dsroute/v1/routing.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单条路由规则
type RouteRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 路由前缀，空字符串表示默认匹配
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// 目标连接池名称
	Pool          string `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRule) Reset() {
	*x = RouteRule{}
	mi := &file_api_proto_dsroute_v1_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRule) ProtoMessage() {}

func (x *RouteRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsroute_v1_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRule.ProtoReflect.Descriptor instead.
func (*RouteRule) Descriptor() ([]byte, []int) {
	return file_api_proto_dsroute_v1_routing_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRule) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *RouteRule) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

// MySQL 路由配置
type MySQLRoutes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RouteRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySQLRoutes) Reset() {
	*x = MySQLRoutes{}
	mi := &file_api_proto_dsroute_v1_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySQLRoutes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLRoutes) ProtoMessage() {}

func (x *MySQLRoutes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsroute_v1_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLRoutes.ProtoReflect.Descriptor instead.
func (*MySQLRoutes) Descriptor() ([]byte, []int) {
	return file_api_proto_dsroute_v1_routing_proto_rawDescGZIP(), []int{1}
}

func (x *MySQLRoutes) GetRules() []*RouteRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// Redis 路由配置
type RedisRoutes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RouteRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisRoutes) Reset() {
	*x = RedisRoutes{}
	mi := &file_api_proto_dsroute_v1_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisRoutes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisRoutes) ProtoMessage() {}

func (x *RedisRoutes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsroute_v1_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisRoutes.ProtoReflect.Descriptor instead.
func (*RedisRoutes) Descriptor() ([]byte, []int) {
	return file_api_proto_dsroute_v1_routing_proto_rawDescGZIP(), []int{2}
}

func (x *RedisRoutes) GetRules() []*RouteRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

var File_api_proto_dsroute_v1_routing_proto protoreflect.FileDescriptor

const file_api_proto_dsroute_v1_routing_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/dsroute/v1/routing.proto\x12\n" +
	"dsroute.v1\"7\n" +
	"\tRouteRule\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\":\n" +
	"\vMySQLRoutes\x12+\n" +
	"\x05rules\x18\x01 \x03(\v2\x15.dsroute.v1.RouteRuleR\x05rules\":\n" +
	"\vRedisRoutes\x12+\n" +
	"\x05rules\x18\x01 \x03(\v2\x15.dsroute.v1.RouteRuleR\x05rulesB/Z-github.com/CBookShu/kd48/api/proto/dsroute/v1b\x06proto3"

var (
	file_api_proto_dsroute_v1_routing_proto_rawDescOnce sync.Once
	file_api_proto_dsroute_v1_routing_proto_rawDescData []byte
)

func file_api_proto_dsroute_v1_routing_proto_rawDescGZIP() []byte {
	file_api_proto_dsroute_v1_routing_proto_rawDescOnce.Do(func() {
		file_api_proto_dsroute_v1_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dsroute_v1_routing_proto_rawDesc), len(file_api_proto_dsroute_v1_routing_proto_rawDesc)))
	})
	return file_api_proto_dsroute_v1_routing_proto_rawDescData
}

var file_api_proto_dsroute_v1_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_dsroute_v1_routing_proto_goTypes = []any{
	(*RouteRule)(nil),   // 0: dsroute.v1.RouteRule
	(*MySQLRoutes)(nil), // 1: dsroute.v1.MySQLRoutes
	(*RedisRoutes)(nil), // 2: dsroute.v1.RedisRoutes
}
var file_api_proto_dsroute_v1_routing_proto_depIdxs = []int32{
	0, // 0: dsroute.v1.MySQLRoutes.rules:type_name -> dsroute.v1.RouteRule
	0, // 1: dsroute.v1.RedisRoutes.rules:type_name -> dsroute.v1.RouteRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_dsroute_v1_routing_proto_init() }
func file_api_proto_dsroute_v1_routing_proto_init() {
	if File_api_proto_dsroute_v1_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dsroute_v1_routing_proto_rawDesc), len(file_api_proto_dsroute_v1_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_dsroute_v1_routing_proto_goTypes,
		DependencyIndexes: file_api_proto_dsroute_v1_routing_proto_depIdxs,
		MessageInfos:      file_api_proto_dsroute_v1_routing_proto_msgTypes,
	}.Build()
	File_api_proto_dsroute_v1_routing_proto = out.File
	file_api_proto_dsroute_v1_routing_proto_goTypes = nil
	file_api_proto_dsroute_v1_routing_proto_depIdxs = nil
}
